# Generated by Django 6.0.5 on 2026-05-13 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AimSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpi', models.PositiveIntegerField(default=800)),
                ('valorant_sensitivity', models.FloatField(default=0.35)),
                ('mousepad_size_cm', models.PositiveIntegerField(blank=True, null=True)),
                ('training_duration', models.PositiveIntegerField(default=60)),
                ('show_hit_feedback', models.BooleanField(default=True)),
                ('enable_sound_effects', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aim_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('rank', models.CharField(default='Recruit', max_length=50)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('best_score', models.PositiveIntegerField(default=0)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progression', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
