# Generated by Django 6.0.5 on 2026-05-13 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aim', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_id', models.CharField(max_length=50)),
                ('level_name', models.CharField(max_length=100)),
                ('score', models.PositiveIntegerField(default=0)),
                ('accuracy', models.PositiveIntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('awarded_rank', models.CharField(blank=True, default='', max_length=50)),
                ('awarded_xp', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SensitivityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpi', models.PositiveIntegerField(default=800)),
                ('sensitivity', models.FloatField(default=0.35)),
                ('edpi', models.PositiveIntegerField(default=280)),
                ('hits', models.PositiveIntegerField(default=0)),
                ('misses', models.PositiveIntegerField(default=0)),
                ('total_shots', models.PositiveIntegerField(default=0)),
                ('accuracy', models.PositiveIntegerField(default=0)),
                ('overflicks', models.PositiveIntegerField(default=0)),
                ('underflicks', models.PositiveIntegerField(default=0)),
                ('recommendation', models.CharField(default='keep', max_length=20)),
                ('recommended_sensitivity', models.FloatField(default=0.35)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensitivity_assessments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=50)),
                ('difficulty', models.CharField(max_length=50)),
                ('hits', models.PositiveIntegerField(default=0)),
                ('misses', models.PositiveIntegerField(default=0)),
                ('total_clicks', models.PositiveIntegerField(default=0)),
                ('accuracy', models.PositiveIntegerField(default=0)),
                ('shots_per_minute', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveIntegerField(default=0)),
                ('sensitivity', models.FloatField(default=0.35)),
                ('edpi', models.PositiveIntegerField(default=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WarmupSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_seconds', models.PositiveIntegerField(default=300)),
                ('completed', models.BooleanField(default=False)),
                ('score', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warmup_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
